# Generated by Django 4.2.7 on 2024-10-30 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacja1', '0002_remove_produkt_nazwa'),
    ]

    operations = [
        migrations.AddField(
            model_name='produkt',
            name='nazwa',
            field=models.CharField(default='Null', max_length=100),
        ),
        migrations.AlterField(
            model_name='produkt',
            name='opis',
            field=models.CharField(default='Null', max_length=100),
        ),
    ]
