# Generated by Django 4.2.7 on 2024-10-30 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacja1', '0003_produkt_nazwa_alter_produkt_opis'),
    ]

    operations = [
        migrations.AddField(
            model_name='produkt',
            name='cena',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='Zdjecie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obraz', models.ImageField(upload_to='photos/')),
                ('produkt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aplikacja1.produkt')),
            ],
        ),
    ]
