# Generated by Django 4.2.7 on 2024-10-30 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacja1', '0004_produkt_cena_zdjecie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zdjecie',
            name='produkt',
        ),
        migrations.AddField(
            model_name='produkt',
            name='obraz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aplikacja1.zdjecie'),
        ),
    ]
