# Generated by Django 4.2.7 on 2024-11-13 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacja1', '0005_remove_zdjecie_produkt_produkt_obraz'),
    ]

    operations = [
        migrations.CreateModel(
            name='koszyk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kupujacy', models.CharField(max_length=100)),
                ('zamowiony_produkt', models.CharField(default='Null', max_length=100)),
            ],
        ),
    ]
